Repository silx-kit/silx, pull requests merged in 2019-12, with the labels that each got.

#2803 Add more change signaling to plot ROI
  examples/plotInteractiveImageROI.py
  silx/gui/plot/items/core.py
  silx/gui/plot/items/roi.py
  silx/gui/plot/tools/roi.py
Labels: ready to merge

#2807 [requirements] add Cython
  requirements.txt
Labels: ready to merge

#2800 Rework matplotlib backend rendering (and picking)
  silx/gui/plot/PlotWidget.py
  silx/gui/plot/backends/BackendBase.py
  silx/gui/plot/backends/BackendMatplotlib.py
  silx/gui/plot/backends/BackendOpenGL.py
Labels: ready to merge

#2811 Fix scatterview profile interaction
  silx/gui/plot/ScatterView.py
  silx/gui/plot/tools/profile/_BaseProfileToolBar.py
Labels: ready to merge

#2810 Scatter plot regular grid visualization mode
  silx/gui/plot/items/core.py
  silx/gui/plot/items/scatter.py
  silx/gui/plot3d/items/scatter.py
Labels: ready to merge

#2813 Add action to save stack of images
  silx/gui/plot/StackView.py
  silx/gui/plot/actions/io.py
Labels: ready to merge

#2815 Scatter regular grid visualization parameters
  silx/gui/plot/items/core.py
  silx/gui/plot/items/scatter.py
Labels: ready to merge

#2814 Expose ColormapNameComboBox in silx.gui.widgets
  silx/gui/dialog/ColormapDialog.py
  silx/gui/widgets/ColormapNameComboBox.py
Labels: ready to merge

#2817 [IO] Specfile. Increase maximum number of motors
  silx/io/specfile/src/sflabel.c
Labels: ready to merge

#2820 Scatter regular grid update
  silx/gui/plot/items/core.py
  silx/gui/plot/items/scatter.py
  silx/gui/plot/test/testPlotWidget.py
Labels: ready to merge

#2822 [plot] Make code compatible with numpy 1.12
  silx/gui/plot/backends/BackendMatplotlib.py
  silx/gui/plot/backends/glutils/GLPlotTriangles.py
Labels: ready to merge

#2824 Add an irregular grid rendering mode for scatter plots
  silx/gui/plot/items/core.py
  silx/gui/plot/items/scatter.py
Labels: ready to merge

#2823 Create BoundingRect item
  silx/gui/plot/PlotWidget.py
  silx/gui/plot/items/__init__.py
  silx/gui/plot/items/shape.py
  silx/gui/plot/test/testPlotWidget.py
Labels: ready to merge

#2675 [plot3d] Add colormapped isosurface to ComplexField3D
  silx/gui/plot/items/complex.py
  silx/gui/plot/items/core.py
  silx/gui/plot3d/_model/items.py
  silx/gui/plot3d/items/volume.py
  silx/gui/plot3d/scene/primitives.py
Labels: ready to merge

#2829 Rework plot backend picking especially for matplotlib
  silx/gui/plot/backends/BackendBase.py
  silx/gui/plot/backends/BackendMatplotlib.py
  silx/gui/plot/backends/BackendOpenGL.py
  silx/gui/plot/items/complex.py
  silx/gui/plot/items/curve.py
  silx/gui/plot/items/histogram.py
  silx/gui/plot/items/image.py
  silx/gui/plot/items/marker.py
  silx/gui/plot/items/scatter.py
Labels: ready to merge

#2834 [plot] A four-element array leads to a comparison error.
  silx/gui/plot/PlotInteraction.py
Labels: ready to merge

#2832 [gui][StackView] fix autoscale=True option
  silx/gui/plot/StackView.py
Labels: ready to merge

#2833 Update CHANGELOG.rst
  CHANGELOG.rst
Labels: question

#2837 Bump version 0.13.0dev
  CHANGELOG.rst
  ci/appveyor.yml
  setup.py
  version.py
Labels: ready to merge

#2839 Fix none and log bound
  silx/gui/plot/items/shape.py
Labels: bug

#2849 [mpl backend] Fix mouse-y location to integer
  silx/gui/plot/backends/BackendMatplotlib.py
Labels: ready to merge

#2851 [plot] ColormapDialog: Add z order to plot items to ensure rendering order
  silx/gui/dialog/ColormapDialog.py
Labels: ready to merge

#2852 [plot] Fix plot add invisible item
  silx/gui/plot/PlotWidget.py
Labels: ready to merge

#2853 [plot] Fix matplotlib crosshair rendering
  silx/gui/plot/backends/BackendMatplotlib.py
Labels: ready to merge
