Repository silx-kit/silx, pull requests merged in 2020-04, with the labels that each got.

#2989 Fix tests using assertEqual
  silx/gui/plot/test/testCurvesROIWidget.py
  silx/gui/plot/test/testStats.py
Labels: quality, ready to merge

#2480 [ImageStack] Add ImageStack.py file
  examples/imageStack.py
  silx/gui/plot/ImageStack.py
  silx/gui/plot/test/__init__.py
  silx/gui/plot/test/testImageStack.py
  silx/gui/widgets/UrlSelectionTable.py
Labels: ready to merge

#2986 Use icon for mask tools
  silx/gui/plot/_BaseMaskToolsWidget.py
  silx/resources/gui/icons/mask-clear-all.png
  silx/resources/gui/icons/mask-clear-all.svg
  silx/resources/gui/icons/mask-clear.png
  silx/resources/gui/icons/mask-clear.svg
  silx/resources/gui/icons/mask-invert.png
  silx/resources/gui/icons/mask-invert.svg
Labels: ready to merge

#2991 Fix out-of-bound row/column indices
  silx/gui/plot/backends/BackendMatplotlib.py
Labels: ready to merge

#2923 Add option to select the reduction function for "histogram" of scatter plot
  silx/gui/plot/PlotToolButtons.py
  silx/gui/plot/ScatterView.py
  silx/gui/plot/items/core.py
  silx/gui/plot/items/scatter.py
  silx/gui/plot/test/testPlotWidget.py
Labels: ready to merge

#2993 Fix not equal test
  silx/io/url.py
Labels: ready to merge

#2995 Fix download link for miniconda on macos
  ci/before_install-osx.sh
Labels: ready to merge

#2994 Rework the StackView with a stack image plot item
  silx/gui/data/DataViews.py
  silx/gui/data/NXdataWidgets.py
  silx/gui/plot/Profile.py
  silx/gui/plot/StackView.py
  silx/gui/plot/items/image.py
  silx/gui/plot/test/testProfile.py
  silx/utils/array_like.py
Labels: ready to merge

#2980 [plot] Keep profile window always on top
  silx/gui/plot/ProfileMainWindow.py
Labels: ready to merge

#2984 [plot] Make mpl backend resilient in case PlotWidget already destroyed
  silx/gui/plot/backends/BackendMatplotlib.py
Labels: ready to merge

#2999 [silx view] When NXdata title is defined, do not append dataset name
  silx/gui/data/NXdataWidgets.py
Labels: ready to merge

#3000 Add a isDragged method to plot marker items
  silx/gui/plot/items/marker.py
Labels: ready to merge

#3002 [plot] Fix PlotWidget.getInteractiveMode
  silx/gui/plot/PlotInteraction.py
  silx/gui/plot/PlotWidget.py
Labels: ready to merge

#3009 Remove print
  silx/gui/plot/test/testCurvesROIWidget.py
Labels: quality, ready to merge

#3007 [roi] Create horizontal range ROI
  silx/gui/plot/items/roi.py
  silx/gui/plot/tools/roi.py
  silx/gui/plot/tools/test/testROI.py
  silx/resources/gui/icons/add-range-horizontal.png
  silx/resources/gui/icons/add-range-horizontal.svg
Labels: enhancement, ready to merge

#3012 Fix import
  silx/io/url.py
Labels: quality, ready to merge

#3010 [plot] Add support for more colormap normalization
  silx/gui/colors.py
  silx/gui/dialog/ColormapDialog.py
  silx/gui/dialog/test/test_colormapdialog.py
  silx/gui/plot/ColorBar.py
  silx/gui/plot/backends/BackendOpenGL.py
  silx/gui/plot/backends/glutils/GLPlotImage.py
  silx/gui/plot/matplotlib/Colormap.py
  silx/gui/plot3d/scene/function.py
Labels: ready to merge

#3008 [roi] Allow to select a ROI
  silx/gui/plot/CurvesROIWidget.py
  silx/gui/plot/PlotInteraction.py
  silx/gui/plot/items/core.py
  silx/gui/plot/items/roi.py
  silx/gui/plot/tools/roi.py
  silx/gui/plot/tools/test/testROI.py
Labels: enhancement, ready to merge

#3014 [plot] Helper to set back the previous mode used
  silx/gui/plot/PlotWidget.py
Labels: ready to merge

#3017 Test dicttoh5 flat dict
  silx/io/dictdump.py
  silx/io/test/test_dictdump.py
Labels: ready to merge

#3018 [roi] Provide an action to create new ROIs
  silx/gui/plot/tools/roi.py
Labels: ready to merge

#2988 Rework profile tool
  doc/source/modules/gui/plot/index.rst
  doc/source/modules/gui/plot/tools/img/CurveLegendsWidget.png
  doc/source/modules/gui/plot/tools/img/linearColorbar.png
  doc/source/modules/gui/plot/tools/index.rst
  doc/source/modules/gui/plot/tools/profile.rst
  examples/plotProfile.py
  silx/gui/plot/PlotToolButtons.py
  silx/gui/plot/PlotWidget.py
  silx/gui/plot/Profile.py
  silx/gui/plot/ProfileMainWindow.py
  silx/gui/plot/items/__init__.py
  silx/gui/plot/tools/profile/core.py
  silx/gui/plot/tools/profile/editors.py
  silx/gui/plot/tools/profile/manager.py
  silx/gui/plot/tools/profile/rois.py
  silx/gui/plot/tools/roi.py
  silx/gui/plot/tools/test/__init__.py
  silx/gui/plot/tools/test/testProfile.py
  silx/resources/gui/icons/shape-cross.png
  silx/resources/gui/icons/shape-cross.svg
  silx/resources/gui/icons/slice-cross.png
  silx/resources/gui/icons/slice-cross.svg
  silx/resources/gui/icons/slice-horizontal.png
  silx/resources/gui/icons/slice-horizontal.svg
  silx/resources/gui/icons/slice-vertical.png
  silx/resources/gui/icons/slice-vertical.svg
Labels: enhancement, work in progress

#3020 Improve internal roi objects
  silx/gui/plot/PlotWidget.py
  silx/gui/plot/items/roi.py
Labels: enhancement

#3024 Fixes compatibility with h5py <2.9 (and debian10)
  silx/io/test/test_dictdump.py
Labels: ready to merge
