Repository silx-kit/silx, pull requests merged in 2020-12, with the labels that each got.

#3307 [OpenCL] Expose the workgroup size min, max and memory usage
  silx/opencl/common.py
  silx/opencl/test/test_addition.py
Labels: difficulty:Easy, ready to merge

#3308 Deprecation warning in 3.9 & Fix the sift algorithm
  silx/gui/plot/actions/control.py
  silx/opencl/sift/plan.py
Labels: difficulty:Easy, ready to merge

#3310 Few clean up on mask tool
  silx/gui/plot/MaskToolsWidget.py
  silx/gui/plot/ScatterMaskToolsWidget.py
  silx/gui/plot/_BaseMaskToolsWidget.py
Labels: ready to merge

#3311 silx view: Changed NXdata image to keep data aspect ratio by default for images
  silx/gui/data/NXdataWidgets.py
Labels: ready to merge

#3313 Relax FFT tests tolerance
  silx/math/fft/test/test_fft.py
Labels: ready to merge

#3318 silx.gui.plot.PlotWidget: Enhanced matplotlib backend high-dpi screen support by using Qt coordinates
  silx/gui/plot/backends/BackendMatplotlib.py
Labels: ready to merge

#3320 silx.gui.plot.PlotWidget: Fixed `setBackend` method.
  silx/gui/plot/PlotWidget.py
Labels: ready to merge

#3323 compare integers, not strings
  silx/io/test/test_utils.py
  silx/io/utils.py
Labels: difficulty:Easy, ready to merge

#3325 This times it is belt & suspenders
  silx/io/test/test_utils.py
  silx/io/utils.py
Labels: difficulty:Easy, ready to merge

#3326 Expose minimum (reasonable) workgroup size
  silx/opencl/processing.py
Labels: difficulty:Easy

#3328 Fixed numpy 1.20 compatibility
  doc/source/Tutorials/fit.rst
  silx/gui/colors.py
  silx/gui/data/test/test_dataviewer.py
  silx/gui/fit/BackgroundWidget.py
  silx/gui/fit/FitWidget.py
  silx/gui/plot/ComplexImageView.py
  silx/gui/plot/CurvesROIWidget.py
  silx/gui/plot/MaskToolsWidget.py
  silx/gui/plot/ScatterMaskToolsWidget.py
  silx/gui/plot/_BaseMaskToolsWidget.py
  silx/gui/plot/backends/BackendMatplotlib.py
  silx/gui/plot/items/_pick.py
  silx/gui/plot/items/core.py
  silx/gui/plot/items/histogram.py
  silx/gui/plot/items/scatter.py
  silx/gui/plot/stats/stats.py
  silx/gui/plot/test/testComplexImageView.py
  silx/gui/plot/test/testPlotWidget.py
  silx/gui/plot/tools/profile/rois.py
  silx/gui/plot3d/ScalarFieldView.py
  silx/gui/plot3d/items/_pick.py
  silx/gui/plot3d/items/volume.py
  silx/gui/plot3d/scene/utils.py
  silx/io/commonh5.py
  silx/io/dictdump.py
  silx/io/fabioh5.py
  silx/math/fit/bgtheories.py
  silx/math/fit/fitmanager.py
  silx/math/fit/fittheories.py
  silx/math/fit/functions.pyx
  silx/math/fit/leastsq.py
  silx/math/fit/test/test_fit.py
  silx/math/fit/test/test_fitmanager.py
  silx/opencl/projection.py
  silx/sx/_plot.py
Labels: ready to merge

#3330 silx.gui.plot: Fixed `PlotWindow` display of the colorbar
  silx/gui/plot/ColorBar.py
Labels: ready to merge

#3333 Fix 3332 - issue with silx view when NXclass attribute is not recognized
  silx/gui/hdf5/Hdf5Item.py
Labels: bug, ready to merge

#3334 Fixed interactive tests on Windows10
  silx/gui/plot/test/testMaskToolsWidget.py
  silx/gui/plot/test/testPlotInteraction.py
  silx/gui/plot/test/testScatterMaskToolsWidget.py
  silx/gui/plot/tools/test/testROI.py
Labels: ready to merge

#3336 silx.gui.plot: Fixed RegionOfInterest `contains`
  CHANGELOG.rst
  silx/gui/plot/items/_roi_base.py
  silx/gui/plot/items/roi.py
  silx/gui/plot/tools/test/testROI.py
Labels: ready to merge

#3286 Implement mask for bilinear interpolation
  silx/image/bilinear.pyx
  silx/image/test/test_bilinear.py
Labels: ready to merge
