Repository silx-kit/silx, pull requests merged in 2020-11, with the labels that each got.

#3239 Use widget QFontMetrics
  silx/gui/widgets/ElidedLabel.py
Labels: ready to merge

#3240 HDF5 strings: handle h5py 2.x and 3.x
  silx/app/test/test_convert.py
  silx/gui/data/test/test_textformatter.py
  silx/io/dictdump.py
  silx/io/nxdata/parse.py
  silx/io/test/test_dictdump.py
  silx/io/test/test_spectoh5.py
  silx/io/test/test_utils.py
  silx/io/utils.py
Labels: ready to merge

#3248 silx.gui.plot.PlotWidget: Fixed OpenGL backend image display with sqrt colormap normalization
  silx/gui/plot/backends/glutils/GLPlotImage.py
Labels: ready to merge

#3250 Workaround to use only Qt5.7 API
  silx/gui/plot/tools/profile/manager.py
Labels: ready to merge

#3247 CI: Remove pin-pointing to h5py<3
  ci/requirements-pinned.txt
Labels: ready to merge

#3251 [io][dictdump] handle providing numpy arrays of 'numbers'
  silx/io/dictdump.py
  silx/io/test/test_dictdump.py
Labels: bug, ready to merge

#3253 silx.gui.data: Make TextFormatter compatible with h5py>=3
  silx/gui/data/TextFormatter.py
  silx/gui/data/test/test_textformatter.py
  tools/create_h5_sample.py
Labels: ready to merge

#3255 silx.gui.plot.PlotWidget: Added `PlotWidget.[get|set]Backend` enabling switching backend
  silx/gui/plot/ColorBar.py
  silx/gui/plot/ImageView.py
  silx/gui/plot/PlotWidget.py
  silx/gui/plot/PlotWindow.py
  silx/gui/plot/backends/BackendBase.py
  silx/gui/plot/test/testPlotWidget.py
  silx/gui/plot/test/testPlotWindow.py
Labels: ready to merge

#3205 silx.gui: Added lazy update handling of OpenGL textures
  silx/gui/_glutils/FramebufferTexture.py
  silx/gui/_glutils/Texture.py
  silx/gui/plot/backends/glutils/GLPlotImage.py
  silx/gui/plot/backends/glutils/GLText.py
  silx/gui/plot/backends/glutils/GLTexture.py
  silx/gui/plot3d/scene/function.py
  silx/gui/plot3d/scene/primitives.py
  silx/gui/plot3d/scene/text.py
Labels: ready to merge

#3259 silx.gui.plot.PlotWidget: Fixed support of shapes with multiple polygons in the OpenGL backend.
  silx/gui/plot/backends/BackendOpenGL.py
  silx/gui/plot/backends/glutils/GLPlotCurve.py
  silx/gui/plot/test/testPlotWidget.py
Labels: ready to merge

#3261 Plot action to switch on/off OpenGL
  examples/plotInteractiveImageROI.py
  silx/gui/plot/actions/control.py
  silx/resources/gui/icons/backend-opengl.png
  silx/resources/gui/icons/backend-opengl.svg
Labels: ready to merge

#3266 silx.io.url.DataUrl: Fixed slice provided as python slice string
  silx/io/test/test_url.py
  silx/io/url.py
Labels: bug

#3269 Add Qt properties for plot widget colors
  silx/gui/plot/PlotWidget.py
Labels: enhancement

#3273 [OpenCL] Check textures availability
  silx/opencl/backprojection.py
  silx/opencl/common.py
  silx/opencl/convolution.py
  silx/opencl/processing.py
  silx/opencl/projection.py
  silx/opencl/test/test_backprojection.py
  silx/opencl/test/test_convolution.py
  silx/resources/opencl/backproj.cl
  silx/resources/opencl/proj.cl
Labels: ready to merge

#3282 silx.math.colormap: Improved performances for small datasets
  silx/math/colormap.pyx
Labels: ready to merge

#3280 Emit a warning when there is an issue in the Ocl destruction
  silx/opencl/processing.py
Labels: difficulty:Easy, ready to merge

#3283 Split arc roi
  silx/gui/plot/items/_arc_roi.py
  silx/gui/plot/items/_roi_base.py
  silx/gui/plot/items/roi.py
  silx/gui/plot/tools/roi.py
  silx/gui/plot/tools/test/testROI.py
Labels: ready to merge

#3279 silx.gui.plot.Stackview: Replaced `setColormap` `autoscale` argument by `scaleColormapRangeToStack` method
  silx/gui/plot/StackView.py
  silx/gui/plot/test/testStackView.py
Labels: ready to merge

#3291 silx.gui.plot.PlotWidget: Add pan interaction to ROI authoring (`select-draw`) interaction mode
  silx/gui/plot/PlotInteraction.py
Labels: ready to merge

#3293 silx.gui.plot.PlotWidget: Added support of right axis label with OpenGL backend
  silx/gui/plot/backends/BackendOpenGL.py
Labels: ready to merge

#3295 silx.gui.colors: Fixed issue in Colormap stddev3 autoscale mode and avoided warnings
  silx/gui/colors.py
Labels: ready to merge

#3296 Documentation: Updated sample code gallery and screenshots
  doc/source/modules/gui/data/img/ArrayTableWidget.png
  doc/source/modules/gui/data/img/DataViewer.png
  doc/source/modules/gui/plot/img/BasicGridStatsWidget.png
  doc/source/modules/gui/plot/img/LimitsToolBar.png
  doc/source/modules/gui/plot/img/ROIStatsWidget.png
  doc/source/modules/gui/plot/img/logColorbar.png
  doc/source/modules/gui/plot3d/img/SceneWidget.png
  doc/source/modules/gui/widgets/img/FrameBrowser.png
  doc/source/modules/gui/widgets/img/PeriodicCombo.png
  doc/source/modules/gui/widgets/img/PeriodicList.png
  doc/source/modules/gui/widgets/img/PeriodicTable.png
  doc/source/modules/gui/widgets/img/TableWidget.png
  doc/source/modules/gui/widgets/img/ThreadPoolPushButton.png
  doc/source/modules/gui/widgets/img/WaitingPushButton.png
  doc/source/modules/io/specfile.rst
  doc/source/sample_code/img/plotROIStats.png
  doc/source/sample_code/index.rst
Labels: ready to merge

#3305 Deprecation warning in 3.9
  silx/gui/plot/actions/control.py
Labels: difficulty:Easy, ready to merge

#3304 [gui][Imagestack] fix setUrls if no url provided
  silx/gui/plot/ImageStack.py
Labels: bug, ready to merge

#3306 Fix the sift algorithm
  silx/opencl/sift/plan.py
Labels: difficulty:Easy, ready to merge
