Repository silx-kit/silx, pull requests merged in 2021-03, with the labels that each got.

#3376 dicttoh5 overwrite behavior
  silx/io/dictdump.py
  silx/io/test/test_dictdump.py
Labels: ready to merge

#3389 silx.gui.widgets: Fixed `FlowLayout` issue
  silx/gui/widgets/FlowLayout.py
Labels: ready to merge

#3393 Returns the records together with the logging exception
  silx/utils/test/test_testutils.py
  silx/utils/testutils.py
Labels: enhancement

#3387 Documentation: Fixed build warnings
  doc/source/modules/io/h5py_utils.rst
  silx/io/h5py_utils.py
Labels: ready to merge

#3386 silx.gui.plot3d: Added `HeightMapData` and `HeightMapRGBA` items
  doc/source/modules/gui/plot3d/items.rst
  silx/gui/plot3d/items/__init__.py
  silx/gui/plot3d/items/image.py
  silx/gui/plot3d/test/testSceneWindow.py
  silx/gui/plot3d/tools/PositionInfoWidget.py
Labels: ready to merge

#3397 silx.gui.plot3d: Fixed height map items picking
  silx/gui/plot3d/items/image.py
Labels: bug, ready to merge

#3395 3394 opencl statistics
  silx/opencl/codec/test/test_byte_offset.py
  silx/opencl/processing.py
Labels: enhancement, ready to merge

#3396 silx.gui.plot: Fixed histogram action by removing histogram when there is no active image or scatter
  silx/gui/plot/actions/histogram.py
Labels: question, ready to merge

#3400 silx.gui.plot: Added `Plotwidget.discarditem` method
  silx/gui/plot/PlotWidget.py
  silx/gui/plot/test/testPlotWidget.py
Labels: ready to merge

#3398 silx.gui.plot.stats: Fixed stats for histogram plot items
  silx/gui/plot/stats/stats.py
Labels: ready to merge

#3403 silx.gui.plot.ColorBar: Fixed issue when deleting attached PlotWidget
  silx/gui/plot/ColorBar.py
Labels: ready to merge

#3401 silx.gui.plot.Plotwidget: Added unified `selection` handler compatible with active item management
  silx/gui/plot/PlotWidget.py
  silx/gui/plot/test/testPlotWidget.py
Labels: ready to merge

#3399 silx.gui.plot: Enhanced `PositionInfo` information labels layout
  silx/gui/plot/tools/PositionInfo.py
Labels: ready to merge

#3391 silx.gui.plot: Added some statistic indicators in `PixelIntensitiesHistoAction` action
  silx/gui/plot/actions/histogram.py
  silx/gui/plot/test/testPixelIntensityHistoAction.py
Labels: ready to merge

#3405 silx.gui.plot: Fixed histogram picking, Enabled `PositionInfo` snapping to histogram
  silx/gui/plot/actions/histogram.py
  silx/gui/plot/items/histogram.py
  silx/gui/plot/tools/PositionInfo.py
Labels: ready to merge

#3409 Prepare 0.15.0rc1: Updated changelog and bumped version
  CHANGELOG.rst
  version.py
Labels: ready to merge

#3414 silx.gui.plot3d: Fixed `ImageRgba` alpha channel display
  silx/gui/plot3d/scene/primitives.py
Labels: ready to merge

#3418 silx view: Support very large 1D datasets in "Raw" table view
  silx/gui/data/RecordTableView.py
Labels: ready to merge

#3419 silx.gui.data.ArrayTableWidget: Added support of array clipping if data is too large
  silx/gui/data/ArrayTableModel.py
  silx/gui/data/test/test_arraywidget.py
Labels: ready to merge

#3416 silx.gui.plot.PlotWidget: Fixed rendering; Doc: Updated sample code.
  examples/stackView.py
  silx/gui/plot/backends/BackendMatplotlib.py
Labels: ready to merge

#3422 Fix retry timeout tests
  silx/io/test/test_h5py_utils.py
  silx/utils/retry.py
  silx/utils/test/test_retry.py
Labels: ready to merge

#3426 silx.utils.retry: Fixed subprocess retry on Linux -backport 0.15
  silx/io/test/test_h5py_utils.py
  silx/utils/retry.py
  silx/utils/test/test_retry.py
Labels: ready to merge

#3428 silx.utils.html: Depreacted in favor of python3 `html` package
  examples/hdf5widget.py
  silx/gui/hdf5/_utils.py
  silx/utils/html.py
  silx/utils/test/__init__.py
  silx/utils/test/test_html.py
Labels: ready to merge

#3427 Misc: Updated changelog and bump version
  CHANGELOG.rst
  version.py
Labels: ready to merge

#3430 Port v0.15.0 changes from 0.15 branch
  CHANGELOG.rst
  examples/stackView.py
  silx/__main__.py
  silx/app/view/test/test_launcher.py
  silx/gui/data/ArrayTableModel.py
  silx/gui/data/RecordTableView.py
  silx/gui/data/test/test_arraywidget.py
  silx/gui/plot/backends/BackendMatplotlib.py
  silx/gui/plot3d/scene/primitives.py
Labels: ready to merge

#3408 silx.gui.plot.actions.histogram: Refactor `PixelIntensitiesHistoAction` to use `PlotWidget.selection`
  src/silx/gui/plot/actions/histogram.py
Labels: ready to merge
