Repository silx-kit/silx, pull requests merged in 2021-06, with the labels that each got.

#3476 Fixed support of numpy 1.21
  setup.py
Labels: ready to merge

#3475 [silx view] update about window: add h5py and HDF5 version
  src/silx/app/view/About.py
Labels: ready to merge

#3478 Fixed SVG icons for Qt6
  src/silx/resources/gui/icons/compare-align-auto.svg
  src/silx/resources/gui/icons/compare-align-center.svg
  src/silx/resources/gui/icons/compare-align-origin.svg
  src/silx/resources/gui/icons/compare-align-stretch.svg
  src/silx/resources/gui/icons/math-peak-search.svg
  src/silx/resources/gui/icons/remove.svg
  src/silx/resources/gui/icons/zoom-back.svg
  src/silx/resources/gui/icons/zoom-in.svg
  src/silx/resources/gui/icons/zoom-original.svg
  src/silx/resources/gui/icons/zoom-out.svg
  src/silx/resources/gui/icons/zoom.svg
Labels: ready to merge

#3480 silx.gui: Qt4 support cleanup
  examples/plotWidget.py
  src/silx/gui/data/HexaTableView.py
  src/silx/gui/plot/ColorBar.py
  src/silx/gui/plot/PlotWindow.py
  src/silx/gui/plot/ScatterView.py
  src/silx/gui/qt/_macosx.py
  src/silx/gui/qt/_pyside_missing.py
  src/silx/gui/widgets/RangeSlider.py
Labels: ready to merge

#3477 [0.15 branch] Prepare v0.15.2
  CHANGELOG.rst
  setup.py
  silx/gui/colors.py
  silx/gui/plot/ImageStack.py
  silx/gui/widgets/UrlSelectionTable.py
  silx/io/spech5.py
  version.py
Labels: ready to merge

#3481 silx.gui: Prepare for Qt6 support
  src/silx/app/view/Viewer.py
  src/silx/gui/colors.py
  src/silx/gui/plot/CompareImages.py
Labels: ready to merge

#3482 silx.gui: clean-up Qt4 support code
  src/silx/app/view/CustomNxdataWidget.py
  src/silx/gui/_glutils/font.py
  src/silx/gui/data/ArrayTableModel.py
  src/silx/gui/data/Hdf5TableView.py
  src/silx/gui/data/HexaTableView.py
  src/silx/gui/data/RecordTableView.py
  src/silx/gui/dialog/AbstractDataFileDialog.py
  src/silx/gui/fit/FitWidget.py
  src/silx/gui/fit/FitWidgets.py
  src/silx/gui/hdf5/Hdf5HeaderView.py
  src/silx/gui/hdf5/Hdf5TreeView.py
  src/silx/gui/plot/CurvesROIWidget.py
  src/silx/gui/plot/ROIStatsWidget.py
  src/silx/gui/plot/StatsWidget.py
  src/silx/gui/plot/backends/BackendOpenGL.py
  src/silx/gui/plot/tools/roi.py
  src/silx/gui/plot3d/ParamTreeView.py
  src/silx/gui/plot3d/Plot3DWidget.py
  src/silx/gui/plot3d/SFViewParamTree.py
  src/silx/gui/utils/testutils.py
  src/silx/gui/widgets/PrintPreview.py
  src/silx/gui/widgets/UrlSelectionTable.py
  src/silx/gui/widgets/test/test_hierarchicaltableview.py
Labels: ready to merge

#3455 silx.gui.plot.ImageView: Fixed issue with profile window size
  src/silx/gui/plot/tools/profile/manager.py
Labels: ready to merge

#3457 silx.gui.plot.ImageView: Fixed profile window, added `setProfileWindowBehavior` method
  src/silx/gui/plot/ImageView.py
  src/silx/gui/plot/Profile.py
  src/silx/gui/plot/test/testImageView.py
Labels: ready to merge

#3490 silx.gui.plot.ImageStack: Removed useless assert
  src/silx/gui/plot/ImageStack.py
Labels: bug

#3472 3451 doubleword
  src/silx/opencl/test/test_doubleword.py
  src/silx/resources/opencl/doubleword.cl
Labels: ready to merge

#3492 silx.gui.plot: Fixed `ArcROI.setGeometry`
  src/silx/gui/plot/items/_arc_roi.py
Labels: ready to merge

#3493 Backports to 0.15: silx.gui.plot: Fixed ArcROI.setGeometry
  CHANGELOG.rst
  silx/gui/plot/items/_arc_roi.py
Labels: ready to merge

#3447 silx.gui.plot.PlotWidget: Optimize regular grid visualisation of scatters
  src/silx/gui/plot/items/scatter.py
Labels: enhancement, ready to merge

#3484 silx.gui: Prepare for Qt6 support (follow-up)
  src/silx/app/view/Viewer.py
  src/silx/gui/plot/tools/roi.py
Labels: ready to merge

#3500 Fix returned keepDataAspectRatioAction
  src/silx/gui/plot/PlotWindow.py
Labels: ready to merge

#3488 Show/hide ImageView side histogram
  examples/imageview.py
  src/silx/gui/plot/ImageView.py
  src/silx/resources/gui/icons/side-histograms.png
  src/silx/resources/gui/icons/side-histograms.svg
Labels: ready to merge
