Repository silx-kit/silx, pull requests merged in 2023-11, with the labels that each got.

#3960 [GUI] Histogram Action. QHoverEvent does not have attribute pos
  src/silx/gui/plot/actions/histogram.py
  src/silx/gui/widgets/RangeSlider.py
Labels: ready to merge

#3967 [CI] Test latest Python 3.12
  ci/appveyor.yml
  ci/requirements-pinned.txt
  src/silx/gui/utils/testutils.py
Labels: ready to merge

#3865 silx.gui.plot.PlotWidget: Use matplotlib tight layout as experimental feature
  src/silx/_config.py
  src/silx/app/view/ApplicationContext.py
  src/silx/app/view/Viewer.py
  src/silx/gui/plot/ImageView.py
  src/silx/gui/plot/backends/BackendMatplotlib.py
Labels: enhancement

#3979 Lazy-loading of multiprocessing module
  src/silx/utils/retry.py
Labels: ready to merge

#3981 silx.gui: Added support for `QT_API` environment variable
  src/silx/gui/qt/__init__.py
  src/silx/gui/qt/_qt.py
Labels: question
